In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("exam_data.csv",encoding="gbk")

In [4]:
df

price  volume       date  Unnamed: 3  Unnamed: 4
0  120.0     300   2022/1/1         NaN         NaN
1   95.0     150   2022/1/2         NaN         NaN
2  110.0     500   2022/1/3         NaN         NaN
3   85.0     200   2022/1/4         NaN         NaN
4  130.0     350   2022/1/5         NaN         NaN
5    NaN     180   2022/1/6         NaN         NaN
6   99.0     210   2022/1/7         NaN         NaN
7  102.0     190   2022/1/8         NaN         NaN
8    NaN     250   2022/1/9         NaN         NaN
9  150.0     400  2022/1/10         NaN         NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   price       8 non-null      float64
 1   volume      10 non-null     int64  
 2   date        10 non-null     object 
 3   Unnamed: 3  0 non-null      float64
 4   Unnamed: 4  0 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes


In [6]:
df_cleaned = df.dropna

In [7]:
df_cleaned

<bound method DataFrame.dropna of    price  volume       date  Unnamed: 3  Unnamed: 4
0  120.0     300   2022/1/1         NaN         NaN
1   95.0     150   2022/1/2         NaN         NaN
2  110.0     500   2022/1/3         NaN         NaN
3   85.0     200   2022/1/4         NaN         NaN
4  130.0     350   2022/1/5         NaN         NaN
5    NaN     180   2022/1/6         NaN         NaN
6   99.0     210   2022/1/7         NaN         NaN
7  102.0     190   2022/1/8         NaN         NaN
8    NaN     250   2022/1/9         NaN         NaN
9  150.0     400  2022/1/10         NaN         NaN>

In [8]:
df_filed = df.fillna(0)

In [9]:
df_filed

price  volume       date  Unnamed: 3  Unnamed: 4
0  120.0     300   2022/1/1         0.0         0.0
1   95.0     150   2022/1/2         0.0         0.0
2  110.0     500   2022/1/3         0.0         0.0
3   85.0     200   2022/1/4         0.0         0.0
4  130.0     350   2022/1/5         0.0         0.0
5    0.0     180   2022/1/6         0.0         0.0
6   99.0     210   2022/1/7         0.0         0.0
7  102.0     190   2022/1/8         0.0         0.0
8    0.0     250   2022/1/9         0.0         0.0
9  150.0     400  2022/1/10         0.0         0.0

In [20]:
df_renamed = df.rename(columns = {"price" : "Price"})
df_renamed
print(df.columns)

Index(['price', 'volume', 'date', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')


In [21]:
filtered_df = df[df["price"] > 100]

In [25]:
average_price_df = df["price"].mean
average_price_df

<bound method Series.mean of 0    120.0
1     95.0
2    110.0
3     85.0
4    130.0
5      NaN
6     99.0
7    102.0
8      NaN
9    150.0
Name: price, dtype: float64>

In [26]:
matrix =np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
add_matrix = matrix + 5
add_matrix

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [30]:
transpose_matrix = matrix.T
transpose_matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])